spring:
  datasource:
    url: jdbc:mysql://root:zdsDUEAkAeLlnCBqndebljPCKqIsRRDO@autorack.proxy.rlwy.net:33921/railway
    username: root
    password: zdsDUEAkAeLlnCBqndebljPCKqIsRRDO

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

  web:
    resources:
      static-locations:
        - file:./assignments/
        - file:./notes/


