spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TuitionToAll?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

  web:
    resources:
      static-locations: file:./assignments/


